import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { IonHeader,IonToolbar,IonTitle,IonButtons,IonBackButton,IonContent } from '@ionic/angular/standalone';
import { ContextKind, PatientClinicalContextService } from '../../services/patient-clinical-context.service';
import { ClinicalIdentityService } from '../../services/clinical-identity.service';
import { normalizeFieldRole } from '../../services/field-role-policy.service';
import { environment } from '../../../environments/environment';

@Component({standalone:true,selector:'app-patient-clinical-context',imports:[CommonModule,FormsModule,IonHeader,IonToolbar,IonTitle,IonButtons,IonBackButton,IonContent],styles:[`section{padding:16px}label{display:block;margin:12px 0}input,textarea,select{display:block;padding:10px;width:100%;border:1px solid #bbb}button{padding:10px;margin:5px}article{padding:12px;border-bottom:1px solid #ddd}.error{color:#a21a25}`],template:`
  <ion-header><ion-toolbar><ion-buttons slot="start"><ion-back-button defaultHref="/tabs/patients"></ion-back-button></ion-buttons><ion-title>Clinical background</ion-title></ion-toolbar></ion-header>
  <ion-content><section><nav><button (click)="select('diagnostic')">Diagnoses</button><button (click)="select('medicalHistory')">Medical history</button><button (click)="select('allergy')">Allergies</button></nav>
    <section *ngIf="instaDev && canWrite"><h2>Insta — isolated DEV test</h2><p>Fictitious referral only. This patient's chart is not sent. AI suggestions require clinical review.</p><button type="button" [disabled]="instaBusy" (click)="testInsta()">{{instaBusy?'Testing Insta…':'Test Insta with fictitious referral'}}</button><p class="error">{{instaError}}</p><article *ngFor="let finding of instaResult?.findings"><h3>{{finding.category}}</h3><p>{{finding.text}}</p><blockquote>{{finding.evidenceQuote}}</blockquote><p>Source: {{finding.sourceId}}</p></article><details *ngIf="instaResult"><summary>Fictitious source pages</summary><p *ngFor="let source of instaResult.sources">Page {{source.page}} — {{source.text}}</p></details></section>
    <button type="button" (click)="openOverview()">Referral overview / pending work</button>
    <section *ngIf="showOverview"><h2>Recorded referral information</h2><article *ngFor="let referral of referrals"><h3>{{referral.sourceOrganizationName || 'Source not recorded'}}</h3><p>{{referral.reasonForReferral}}</p><p>{{referral.woundConcern}}</p><p>Urgency: {{referral.urgency}}</p><p *ngIf="referral.documentsMissing?.length">Missing documents: {{referral.documentsMissing.join(', ')}}</p></article><h2>Pending work</h2><p *ngFor="let task of tasks">{{task.title || task.description || task.type}} — {{dueLabel(task.dueAt)}}</p><p>Recorded facts and tasks only; no inferred diagnosis or new deadline.</p></section>
    <p class="error" role="alert">{{error}}</p><p>Diagnosis entries require provider review using JADE's official ICD-10-CM catalog. No procedure or claim is generated by this entry.</p>
    <article *ngFor="let row of rows"><h2>{{row.code}} {{row.description || row.name || row.diagnostic}}</h2><p>{{row.reaction}} {{row.severity}}</p><p>{{row.onsetType}} {{row.onsetDate}} · Symptom control: {{row.symptomControl ?? 'Not assessed'}}</p><p>{{row.sourceReference || 'Source not recorded'}} · {{row.reviewStatus || 'Needs review'}} · {{row.status || 'Historical record'}}</p><button *ngIf="canWrite && (canApprove || row.reviewStatus!=='approved')" (click)="edit(row)">Review / revise</button></article>
    <p *ngIf="!rows.length">No information recorded. This does not mean no allergies or diagnoses.</p>
    <form *ngIf="canWrite" (ngSubmit)="save()"><h2>Add / revise clinical information</h2>
      <label *ngIf="kind==='diagnostic'">Documented ICD-10-CM code<input name="code" [(ngModel)]="form.code" required></label>
      <label>{{kind==='allergy'?'Allergen / substance':'Documented description'}}<textarea name="description" [(ngModel)]="form.description" required></textarea></label>
      <label>Onset type<select name="onsetType" [(ngModel)]="form.onsetType"><option value="unknown">Unknown</option><option value="onset">Onset</option><option value="exacerbation">Exacerbation</option></select></label><label>Date<input name="onsetDate" type="date" [(ngModel)]="form.onsetDate"></label>
      <label *ngIf="kind==='diagnostic'">Symptom control (0–4)<select name="rating" [(ngModel)]="form.symptomControl"><option [ngValue]="null">Not assessed / not applicable</option><option *ngFor="let rating of ratings; let i=index" [ngValue]="i">{{i}} — {{rating}}</option></select></label>
      <label *ngIf="kind==='allergy'">Reaction<input name="reaction" [(ngModel)]="form.reaction"></label><label *ngIf="kind==='allergy'">Severity<input name="severity" [(ngModel)]="form.severity"></label>
      <label>Source<select name="sourceType" [(ngModel)]="form.sourceType"><option value="staff">Staff documentation</option><option value="referral">Referral</option><option value="patient_report">Patient / caregiver report</option></select></label><label>Supporting source / date / page<textarea name="sourceReference" [(ngModel)]="form.sourceReference" required></textarea></label>
      <label>Status<select name="status" [(ngModel)]="form.status"><option value="active">Active</option><option value="resolved">Resolved / inactive</option><option value="entered_in_error">Entered in error — retained</option></select></label>
      <button type="submit" [disabled]="busy">Save for review</button><button type="button" (click)="reset()">Clear</button>
    </form></section></ion-content>`})
export class PatientClinicalContextPage implements OnInit {
  private route=inject(ActivatedRoute);private service=inject(PatientClinicalContextService);private identity=inject(ClinicalIdentityService);
  patientId='';kind:ContextKind='diagnostic';rows:any[]=[];form:any={};error='';busy=false;canWrite=false;canApprove=false;editingId='';
  ratings=['Asymptomatic; no treatment needed','Well controlled with current therapy','Controlled with difficulty; monitoring needed','Poorly controlled; frequent adjustment needed','Poorly controlled; history of rehospitalization'];
  async ngOnInit(){this.patientId=this.route.snapshot.paramMap.get('patientId') || '';try{const actor=await this.identity.requireCurrentIdentity();const roles=[actor.role,...actor.roles].map(normalizeFieldRole);this.canApprove=roles.some(r=>['np','provider','md','do','physician','admin','org_admin','clinical_admin','super_admin'].includes(r));this.canWrite=this.canApprove || roles.some(r=>['nurse','rn','registered_nurse','lpn'].includes(r));await this.load();}catch(e:any){this.error=e.message;}}
  reset(){this.editingId='';this.form={description:'',code:'',onsetType:'unknown',onsetDate:'',symptomControl:null,sourceType:'staff',sourceReference:'',status:'active',reaction:'',severity:''};}
  private generation=0;
  readonly instaDev=environment.firebase.projectId==='jade-dev-5b0e3';instaBusy=false;instaResult:any=null;instaError='';
  async testInsta(){if(this.instaBusy || !this.instaDev)return;this.instaBusy=true;this.instaResult=null;this.instaError='';try{this.instaResult=await this.service.testInsta();}catch(e:any){this.instaError=e.message || 'Insta unavailable. No chart changed.';}finally{this.instaBusy=false;}}
  showOverview=false;referrals:any[]=[];tasks:any[]=[];
  async openOverview(){this.showOverview=true;try{const overview=await this.service.overview(this.patientId);this.referrals=overview.referrals;this.tasks=overview.tasks;}catch{this.error='Referral / task access unavailable. This does not mean the chart is complete.';}}
  dueLabel(value:any):string{const date=value?.toDate?.() || (value ? new Date(value):null);return date && !isNaN(date.getTime()) ? `${date.getTime()<Date.now() ? 'Overdue: ' : 'Due: '}${date.toLocaleDateString()}` : 'No deadline recorded';}
  async load(){const generation=++this.generation;this.reset();this.rows=[];try{const rows=await this.service.list(this.patientId,this.kind);if(generation===this.generation)this.rows=rows;}catch(e:any){if(generation===this.generation)this.error=e.message;}}
  select(kind:ContextKind){this.kind=kind;void this.load();}
  edit(row:any){this.editingId=row.id;this.form={...row};}
  async save(){if(this.busy)return;this.busy=true;this.error='';try{await this.service.save(this.patientId,this.kind,this.form,this.editingId || undefined);await this.load();}catch(e:any){this.error=e.message;}finally{this.busy=false;}}
}
